services:
  unifipoller:
    image: mdlayher/unifi_exporter:latest
    container_name: unifipoller
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "9130:9130"
    command:
      - "--controller.host=$(UNIFI_CONTROLLER_HOST)"
      - "--controller.port=$(UNIFI_CONTROLLER_PORT)"
      - "--controller.site=$(UNIFI_CONTROLLER_SITE)"
      - "--controller.user=$(UNIFI_CONTROLLER_USER)"
      - "--controller.pass=$(UNIFI_CONTROLLER_PASS)"
      - "--controller.allow-insecure=$(UNIFI_INSECURE_SSL)"
      - "--web.listen-address=:9130"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "9090:9090"
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning

volumes:
  prometheus_data:
  grafana_data:
