services:
  unpoller:
    image: ghcr.io/unpoller/unpoller:latest
    container_name: unpoller
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "9130:9130"
    environment:
      - UP_INFLUXDB_DISABLE=true
      - UP_POLLER_DEBUG=false
      - UP_PROMETHEUS_HTTP_LISTEN=0.0.0.0:9130
      - UP_UNIFI_CONTROLLER_0_URL=${UNIFI_CONTROLLER_URL}
      - UP_UNIFI_CONTROLLER_0_USER=${UNIFI_USER}
      - UP_UNIFI_CONTROLLER_0_PASS=${UNIFI_PASS}
      - UP_UNIFI_CONTROLLER_0_ALLOW_INSECURE=${UNIFI_INSECURE_SSL}

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "9090:9090"
    volumes:
      - prometheus_data:/prometheus
      - type: bind
        source: ./prometheus
        target: /etc/prometheus:ro

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - type: bind
        source: ./grafana/provisioning
        target: /etc/grafana/provisioning:ro

volumes:
  prometheus_data:
  grafana_data:
