
services:
  unpoller:
    image: golift/unpoller:latest
    container_name: unpoller
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "9130:9130"
    environment:
      UP_UNIFI_DEFAULT_ROLE: "default"
      UP_UNIFI_URL: "${UNIFI_CONTROLLER_HOST}:${UNIFI_CONTROLLER_PORT}"
      UP_UNIFI_USER: "${UNIFI_CONTROLLER_USER}"
      UP_UNIFI_PASS: "${UNIFI_CONTROLLER_PASS}"
      UP_INSECURE_SKIP_VERIFY: "${UNIFI_INSECURE_SSL}"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "9090:9090"
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning

volumes:
  prometheus_data:
  grafana_data:
